version: '3.9'
services:
  docker-frontend:
    build: 
      context: angular-crash-2021-frontend
      dockerfile : Dockerfile.dev
    ports:
      - '4200:4200'
    volumes:
      - ./angular-crash-2021-frontend/src:/frontend/src
  docker-backend:
    build: 
      context: angular-crash-2021-backend
      dockerfile : Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./angular-crash-2021-backend:/backend